server:
  port: 8189
  servlet:
    context-path: /user
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:mydatabase;MODE=PostgreSQL
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      settings:
        web-allow-other: false

integrations:
  department-service:
    url: http://localhost:8186/departments
    read-timeout: 10000
    write-timeout: 5000
    connect-timeout: 5000
  job-service:
    url: http://localhost:8182/jobs
    read-timeout: 10000
    write-timeout: 5000
    connect-timeout: 5000
