server:
  port: 8187
  servlet:
    context-path: /itActive-service

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/itActivities
    username: root
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    show-sql: true
  sql:
    init:
      mode: always
#      schema-locations: classpath*:database/initDB.sql
#      data-locations: classpath*:database/populateDB.sql


integrations:
  user-service:
    url: http://localhost:8189/user/
    connect-timeout: 5000
    read-timeout: 10000
    write-timeout: 5000