server:
  port: 8188
  servlet:
    context-path: /order-service

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:mydatabase;MODE=PostgreSQL
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: false

integrations:
  user-service:
    url: http://localhost:8189/user/
    connect-timeout: 5000
    read-timeout: 10000
    write-timeout: 5000