server:
  port: 9000

logging:
  level:
    org.springframework.security: trace

spring:
  security:
    oauth2:
      authorizationserver:
        client:
          oidc-client:
            registration:
              client-id: "web-client"
              client-secret: "{noop}secret"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
              redirect-uris:
                - "http://127.0.0.1:9000/login/oauth2/code/web-client"
              post-logout-redirect-uris:
                - "http://127.0.0.1:9000/authorized"
              scopes:
                - "admin"
                - "user"
              require-authorization-consent: false
