FROM node:18.16.0
WORKDIR ./web_frontend
COPY ./web_frontend/frontend/package.json .
RUN npm i axios react-router-dom mobx mobx-react-lite\
    && npm install react-bootstrap bootstrap\
    && npm i jwt-decode\
    && npm run build
COPY . .
EXPOSE 5000
CMD ["npm", "start"]
