server:
  port: 8083
  servlet:
    context-path: /job

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5483/job
    username: job_user
    password: job_admin
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

integrations:
  department-service:
    url: http://localhost:8189/departments/
    read-timeout: 10000
    write-timeout: 5000
    connect-timeout: 5000