server:
  port: 8192
  servlet:
    context-path: /jobs

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/jobs
    username: postgres
    password: qqq
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

integrations:
  department-service:
    url: http://localhost:8189/departments/
    read-timeout: 10000
    write-timeout: 5000
    connect-timeout: 5000