server:
  port: 8189
  servlet:
    context-path: /departments
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/departments
    username: admin
    password: 123
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
  schema-locations:
    classpath*: database/initDB.sql
  data-locations:
    classpath*: database/populateDB.sql
  h2:
    console:
      enabled: true
      settings:
        web-allow-other: false
integrations:
  user-service:
    url: http://localhost:8190/user/
    read-timeout: 10000
    write-timeout: 5000
    connect-timeout: 5000